### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by ghost** [cuberite/android#68]
Is it possible to use public IP to create a server?

**Comment by bearbin** [comment]
It's not clear what you're asking here. It's not generally possible to use a mobile connection for server hosting, due to CGNAT. This is no matter what server software you use. You can of course use your wifi IP if you set up a static IP and port forwarding in the normal way. 

I am closing this issue as out of scope, but feel free to reopen if this doesn't solve your query.

**Comment by ghost** [comment]
> It's not clear what you're asking here. It's not generally possible to use a mobile connection for server hosting, due to CGNAT. This is no matter what server software you use. You can of course use your wifi IP if you set up a static IP and port forwarding in the normal way.
> 
> I am closing this issue as out of scope, but feel free to reopen if this doesn't solve your query.

I wanted to play with my friends but they are not connected to my private IP and can not be accessed on the server by my IP

**Comment by KingCol13** [comment]
> I wanted to play with my friends but they are not connected to my private IP and can not be accessed on the server by my IP

As stated above you need to:
1. Use a static public IP or set up dynamic DNS. If you do not know how to do this there are plenty of tutorials available online. Then:
2. Set up port forwarding by consulting your router's user manual (Cuberite listens on TCP port 25565 by default, this can be configured in settings.ini)
